# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rdme < Formula
  desc "Execute code snippets directly from Markdown files."
  homepage "https://stateful.com"
  version "0.1.7"

  on_macos do
    if Hardware::CPU.arm?
      url "https://download.stateful.com/rdme/0.1.7/rdme_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "612eb82db5b2c4cc284002d4076855a9753374c5695a62f85e4219bf84d52323"

      def install
        bin.install "rdme"
        (bash_completion/"rdme").write `#{bin}/rdme completion bash`
        (fish_completion/"rdme.fish").write `#{bin}/rdme completion fish`
        (zsh_completion/"_rdme").write `#{bin}/rdme completion zsh`
      end
    end
    if Hardware::CPU.intel?
      url "https://download.stateful.com/rdme/0.1.7/rdme_darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "dbdf8a4b61efaf5fc8aec49a706904dbd6e8366dad393bcf99f97f4f824804e3"

      def install
        bin.install "rdme"
        (bash_completion/"rdme").write `#{bin}/rdme completion bash`
        (fish_completion/"rdme.fish").write `#{bin}/rdme completion fish`
        (zsh_completion/"_rdme").write `#{bin}/rdme completion zsh`
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://download.stateful.com/rdme/0.1.7/rdme_linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "11f37dae4385591fda1edc43002587e2194605618ead7ddd8b8fd9e78651e360"

      def install
        bin.install "rdme"
        (bash_completion/"rdme").write `#{bin}/rdme completion bash`
        (fish_completion/"rdme.fish").write `#{bin}/rdme completion fish`
        (zsh_completion/"_rdme").write `#{bin}/rdme completion zsh`
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://download.stateful.com/rdme/0.1.7/rdme_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "8172518838367385b480b8d8c04f111a5a104baea4600629338271fb1e057638"

      def install
        bin.install "rdme"
        (bash_completion/"rdme").write `#{bin}/rdme completion bash`
        (fish_completion/"rdme.fish").write `#{bin}/rdme completion fish`
        (zsh_completion/"_rdme").write `#{bin}/rdme completion zsh`
      end
    end
  end

  test do
    assert_match "rdme #{version}", shell_output("#{bin}/rdme version")
  end
end
