# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Runme < Formula
  desc "Execute your runbooks, docs, and READMEs."
  homepage "https://runme.dev"
  version "3.2.7"

  on_macos do
    if Hardware::CPU.arm?
      url "https://download.stateful.com/runme/3.2.7/runme_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "f5a0e084c44bb6358a183b4255bbd34d4f7d21c797f9f5fb063a9f09ac4bb6b0"

      def install
        bin.install "runme"
        (bash_completion/"runme").write `#{bin}/runme completion bash`
        (fish_completion/"runme.fish").write `#{bin}/runme completion fish`
        (zsh_completion/"_runme").write `#{bin}/runme completion zsh`
      end
    end
    if Hardware::CPU.intel?
      url "https://download.stateful.com/runme/3.2.7/runme_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "bb6b7da107fce6d693f1b65146de59a62a67c7a3113460975eac8d606fca7b25"

      def install
        bin.install "runme"
        (bash_completion/"runme").write `#{bin}/runme completion bash`
        (fish_completion/"runme.fish").write `#{bin}/runme completion fish`
        (zsh_completion/"_runme").write `#{bin}/runme completion zsh`
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://download.stateful.com/runme/3.2.7/runme_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "c083e50a922613bca7f58d4fa8a621cc8239749fbe3ccd74f92c8e4e9e232954"

      def install
        bin.install "runme"
        (bash_completion/"runme").write `#{bin}/runme completion bash`
        (fish_completion/"runme.fish").write `#{bin}/runme completion fish`
        (zsh_completion/"_runme").write `#{bin}/runme completion zsh`
      end
    end
    if Hardware::CPU.intel?
      url "https://download.stateful.com/runme/3.2.7/runme_linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "0de90e828ce84bf636290b25db69364a019b55c015a514b4be9ecc412c31d6a9"

      def install
        bin.install "runme"
        (bash_completion/"runme").write `#{bin}/runme completion bash`
        (fish_completion/"runme.fish").write `#{bin}/runme completion fish`
        (zsh_completion/"_runme").write `#{bin}/runme completion zsh`
      end
    end
  end

  test do
    assert_match "runme #{version}", shell_output("#{bin}/runme version")
  end
end
