# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Runme < Formula
  desc "Execute your runbooks, docs, and READMEs."
  homepage "https://runme.dev"
  version "2.2.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://download.stateful.com/runme/2.2.1/runme_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "54575ffcedab3a4e499dde3ef3a100a11240713231e1e3ad2f0a8010acdd8bbc"

      def install
        bin.install "runme"
        (bash_completion/"runme").write `#{bin}/runme completion bash`
        (fish_completion/"runme.fish").write `#{bin}/runme completion fish`
        (zsh_completion/"_runme").write `#{bin}/runme completion zsh`
      end
    end
    if Hardware::CPU.intel?
      url "https://download.stateful.com/runme/2.2.1/runme_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "c1efd9cc10f5b94b3457b47b6b3b211043f04abd0a56cdeb7a32a8a6c8afa615"

      def install
        bin.install "runme"
        (bash_completion/"runme").write `#{bin}/runme completion bash`
        (fish_completion/"runme.fish").write `#{bin}/runme completion fish`
        (zsh_completion/"_runme").write `#{bin}/runme completion zsh`
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://download.stateful.com/runme/2.2.1/runme_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "32d0fa7a7eb405ae66ecbe2c8d144ba7787016fd4ef04e2b42fad4048177039e"

      def install
        bin.install "runme"
        (bash_completion/"runme").write `#{bin}/runme completion bash`
        (fish_completion/"runme.fish").write `#{bin}/runme completion fish`
        (zsh_completion/"_runme").write `#{bin}/runme completion zsh`
      end
    end
    if Hardware::CPU.intel?
      url "https://download.stateful.com/runme/2.2.1/runme_linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "9b1fad4da0414144ab9347995f35cf25c927a0b1dda167cb60dc1cbc657349a8"

      def install
        bin.install "runme"
        (bash_completion/"runme").write `#{bin}/runme completion bash`
        (fish_completion/"runme.fish").write `#{bin}/runme completion fish`
        (zsh_completion/"_runme").write `#{bin}/runme completion zsh`
      end
    end
  end

  test do
    assert_match "runme #{version}", shell_output("#{bin}/runme version")
  end
end
