# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Runme < Formula
  desc "Execute your runbooks, docs, and READMEs."
  homepage "https://runme.dev"
  version "3.16.1"

  on_macos do
    on_intel do
      url "https://download.stateful.com/runme/3.16.1/runme_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "5fd55583c9819b8d0fba1223f5da992a32c5c8561cc027d6c6ff91563be97020"

      def install
        bin.install "runme"
        (bash_completion/"runme").write `#{bin}/runme completion bash`
        (fish_completion/"runme.fish").write `#{bin}/runme completion fish`
        (zsh_completion/"_runme").write `#{bin}/runme completion zsh`
      end
    end
    on_arm do
      url "https://download.stateful.com/runme/3.16.1/runme_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "8d1cc5120ddb2ec719315bb0e5e790643284f7ac549ca246fb4f757f500965ee"

      def install
        bin.install "runme"
        (bash_completion/"runme").write `#{bin}/runme completion bash`
        (fish_completion/"runme.fish").write `#{bin}/runme completion fish`
        (zsh_completion/"_runme").write `#{bin}/runme completion zsh`
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://download.stateful.com/runme/3.16.1/runme_linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "8267e01e10ff837b834fa90c2ea89ba2919f5a19dbf9a0f84ffb90fba05af3e9"

        def install
          bin.install "runme"
          (bash_completion/"runme").write `#{bin}/runme completion bash`
          (fish_completion/"runme.fish").write `#{bin}/runme completion fish`
          (zsh_completion/"_runme").write `#{bin}/runme completion zsh`
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://download.stateful.com/runme/3.16.1/runme_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "74d79829d697949a5ef47c95036bca5d987e852976aae01e5de79aa368cf330b"

        def install
          bin.install "runme"
          (bash_completion/"runme").write `#{bin}/runme completion bash`
          (fish_completion/"runme.fish").write `#{bin}/runme completion fish`
          (zsh_completion/"_runme").write `#{bin}/runme completion zsh`
        end
      end
    end
  end

  test do
    assert_match "runme #{version}", shell_output("#{bin}/runme version")
  end
end
