# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stateful < Formula
  desc "CLI for Stateful - Optimize for flow, code better, be happy."
  homepage "https://stateful.com"
  version "0.1.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://download.stateful.com/stateful-cli/0.1.6/stateful_darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "101d212648283ba9540bbd96d781e4c504a98e95a9c08862b7ff6e464b585ec1"

      def install
        bin.install "stateful"
        (bash_completion/"stateful").write `#{bin}/stateful completion bash`
        (fish_completion/"stateful.fish").write `#{bin}/stateful completion fish`
        (zsh_completion/"_stateful").write `#{bin}/stateful completion zsh`
      end
    end
    if Hardware::CPU.arm?
      url "https://download.stateful.com/stateful-cli/0.1.6/stateful_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "763751e7a4e54945dc8db7c0a2ae9100822d9be4a3a3cfcc7a90e485fb533d20"

      def install
        bin.install "stateful"
        (bash_completion/"stateful").write `#{bin}/stateful completion bash`
        (fish_completion/"stateful.fish").write `#{bin}/stateful completion fish`
        (zsh_completion/"_stateful").write `#{bin}/stateful completion zsh`
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://download.stateful.com/stateful-cli/0.1.6/stateful_linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "8e78cf136cdf2f1ddad3e20332e95a94c5d4461c321d1e34254b239b470ac2c0"

      def install
        bin.install "stateful"
        (bash_completion/"stateful").write `#{bin}/stateful completion bash`
        (fish_completion/"stateful.fish").write `#{bin}/stateful completion fish`
        (zsh_completion/"_stateful").write `#{bin}/stateful completion zsh`
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://download.stateful.com/stateful-cli/0.1.6/stateful_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "c01d5668dab32a7b3bfb593300857f419955048ddff168fa43a7da299bba072d"

      def install
        bin.install "stateful"
        (bash_completion/"stateful").write `#{bin}/stateful completion bash`
        (fish_completion/"stateful.fish").write `#{bin}/stateful completion fish`
        (zsh_completion/"_stateful").write `#{bin}/stateful completion zsh`
      end
    end
  end

  test do
    assert_match "stateful #{version}", shell_output("#{bin}/stateful version")
  end
end
