# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stateful < Formula
  desc "CLI for Stateful - Optimize for flow, code better, be happy."
  homepage "https://stateful.com"
  version "0.0.18"

  on_macos do
    if Hardware::CPU.arm?
      url "https://storage.googleapis.com/stateful-cli-artifacts-a1a00b/0.0.18/stateful_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "38e733e39869b64aab0794288f5aff23b0970180b079222d0ebe15e3895af14c"

      def install
        bin.install "stateful"
      end
    end
    if Hardware::CPU.intel?
      url "https://storage.googleapis.com/stateful-cli-artifacts-a1a00b/0.0.18/stateful_darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "741dff3e74024c0f38a93dfac86448a2d5f181b9255702dbdaf40e933cbf584b"

      def install
        bin.install "stateful"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://storage.googleapis.com/stateful-cli-artifacts-a1a00b/0.0.18/stateful_linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "5716f44516d61801865268f93565fe991b1a7f9cd7358da56f5fbd4b27beccb1"

      def install
        bin.install "stateful"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://storage.googleapis.com/stateful-cli-artifacts-a1a00b/0.0.18/stateful_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "da8735dd04a30e383a8df80310127d68d7dc71989b84bde23e5a703d9baf8d31"

      def install
        bin.install "stateful"
      end
    end
  end
end
